### PR TITLE
[TASK] Define inline functions static

### PR DESCRIPTION
**Pull request by simonschaufi**

### CODE REVIEW

**Comment by IchHabRecht** [comment]
Hi @simonschaufi,

Can you please explain what issue this pull requests fixes?

**Comment by IchHabRecht** [comment]
Hi @simonschaufi,

Can you please explain what issue this pull requests fixes?

**Comment by simonschaufi** [comment]
This is a micro optimization because static functions are slightly faster, which I confirmed myself.

**Comment by IchHabRecht** [comment]
Unfortunately you missed some fixes.

**Comment by simonschaufi** [comment]
thanx :partying_face:

**Pull request merged**
